"""Generate a 20-case synthetic stress-test set, drop-in compatible
with the paper's evaluation infrastructure.

Layout per case mirrors the Bugs4Q convention so ``iter_cases()`` and
``run_case()`` can consume it unchanged:

    case_NNN/buggy.py
    case_NNN/fixed.py     <- canonical fix (used as gold by evaluate_candidate)

Cases are short (8-15 lines) and structurally simple, mirroring the
Bugs4Q distribution. Every case is a syntactically valid Qiskit
program containing one or more legacy-API defects from the four
"in-span patchable" categories:

    DeprecatedExecuteAPI    execute(qc, backend=bk)
    LegacyBackendName       'local_*_simulator'
    GetDataMisuse           .get_data(qc)
    IdenGateRename          .iden(...)

The ``fixed.py`` is generated by re-rendering the same template with
NO defects requested, so the diff between buggy.py and fixed.py is
exactly the set of injected legacy patterns rewritten to their modern
equivalents.

Distribution:
    8 single-defect, 7 double, 4 triple, 1 quadruple = 20 cases.
"""
from __future__ import annotations

import argparse
import itertools
import json
import random
from pathlib import Path

DEFECTS = [
    "DeprecatedExecuteAPI",
    "LegacyBackendName",
    "GetDataMisuse",
    "IdenGateRename",
]


# ---------------------------------------------------------------------------
# Defect-rendering helpers
# ---------------------------------------------------------------------------
def _backend_str(legacy: bool, kind: str = "qasm") -> str:
    return f"'local_{kind}_simulator'" if legacy else f"'{kind}_simulator'"


def _execute_call(use_dep: bool) -> str:
    if use_dep:
        return "job = execute(qc, backend=backend)"
    return "job = backend.run(qc)"


def _result_call(use_get_data: bool) -> str:
    if use_get_data:
        return "counts = job.result().get_data(qc)"
    return "counts = job.result().get_counts(qc)"


def _iden_or_id(use_iden: bool, qubit) -> str:
    return f"qc.{'iden' if use_iden else 'id'}({qubit})"


def _render_pair(defects: set[str], render_fn) -> tuple[str, str]:
    """Render the same template twice: once with defects (buggy), once
    without (fixed/gold)."""
    buggy = render_fn(defects)
    fixed = render_fn(set())
    return buggy, fixed


# ---------------------------------------------------------------------------
# Templates: short, terse, Bugs4Q-shaped.
# ---------------------------------------------------------------------------
def _tpl_toplevel(defects):
    """Top-level script (no enclosing function). Most common Bugs4Q shape."""
    def render(d):
        return "\n".join([
            "from qiskit import QuantumCircuit, execute",
            "from qiskit_aer import Aer",
            "qc = QuantumCircuit(2, 2)",
            "qc.h(0)",
            "qc.cx(0, 1)",
            _iden_or_id("IdenGateRename" in d, 0),
            "qc.measure([0, 1], [0, 1])",
            f"backend = Aer.get_backend({_backend_str('LegacyBackendName' in d, 'qasm')})",
            _execute_call("DeprecatedExecuteAPI" in d),
            _result_call("GetDataMisuse" in d),
            "print(counts)",
        ]) + "\n"
    return _render_pair(defects, render)


def _tpl_single_qubit(defects):
    def render(d):
        return "\n".join([
            "from qiskit import QuantumCircuit, execute",
            "from qiskit_aer import Aer",
            "qc = QuantumCircuit(1, 1)",
            "qc.h(0)",
            _iden_or_id("IdenGateRename" in d, 0),
            "qc.measure(0, 0)",
            f"backend = Aer.get_backend({_backend_str('LegacyBackendName' in d, 'qasm')})",
            _execute_call("DeprecatedExecuteAPI" in d),
            _result_call("GetDataMisuse" in d),
            "print(counts)",
        ]) + "\n"
    return _render_pair(defects, render)


def _tpl_register(defects):
    def render(d):
        return "\n".join([
            "from qiskit import QuantumCircuit, QuantumRegister, "
            "ClassicalRegister, execute",
            "from qiskit_aer import Aer",
            "qr = QuantumRegister(2)",
            "cr = ClassicalRegister(2)",
            "qc = QuantumCircuit(qr, cr)",
            "qc.h(qr[0])",
            "qc.cx(qr[0], qr[1])",
            _iden_or_id("IdenGateRename" in d, "qr[0]"),
            "qc.measure(qr, cr)",
            f"backend = Aer.get_backend({_backend_str('LegacyBackendName' in d, 'qasm')})",
            _execute_call("DeprecatedExecuteAPI" in d),
            _result_call("GetDataMisuse" in d),
            "print(counts)",
        ]) + "\n"
    return _render_pair(defects, render)


def _tpl_three_qubit(defects):
    def render(d):
        return "\n".join([
            "from qiskit import QuantumCircuit, execute",
            "from qiskit_aer import Aer",
            "qc = QuantumCircuit(3, 3)",
            "qc.h(0)",
            "qc.cx(0, 1)",
            "qc.cx(1, 2)",
            _iden_or_id("IdenGateRename" in d, 0),
            "qc.measure([0, 1, 2], [0, 1, 2])",
            f"backend = Aer.get_backend({_backend_str('LegacyBackendName' in d, 'qasm')})",
            _execute_call("DeprecatedExecuteAPI" in d),
            _result_call("GetDataMisuse" in d),
            "print(counts)",
        ]) + "\n"
    return _render_pair(defects, render)


def _tpl_function(defects):
    def render(d):
        return "\n".join([
            "from qiskit import QuantumCircuit, execute",
            "from qiskit_aer import Aer",
            "def run():",
            "    qc = QuantumCircuit(2, 2)",
            "    qc.h(0)",
            "    qc.cx(0, 1)",
            f"    {_iden_or_id('IdenGateRename' in d, 0)}",
            "    qc.measure([0, 1], [0, 1])",
            f"    backend = Aer.get_backend({_backend_str('LegacyBackendName' in d, 'qasm')})",
            f"    {_execute_call('DeprecatedExecuteAPI' in d)}",
            f"    {_result_call('GetDataMisuse' in d)}",
            "    return counts",
            "print(run())",
        ]) + "\n"
    return _render_pair(defects, render)


TEMPLATES = [
    ("toplevel",     _tpl_toplevel),
    ("single_qubit", _tpl_single_qubit),
    ("register",     _tpl_register),
    ("three_qubit",  _tpl_three_qubit),
    ("function",     _tpl_function),
]


# ---------------------------------------------------------------------------
# Distribution policy: 8 single + 7 double + 4 triple + 1 quad = 20
# ---------------------------------------------------------------------------
def make_assignment(rng):
    assignment = []
    # 8 singles: 2 of each defect
    for d in DEFECTS:
        assignment.append({d})
        assignment.append({d})
    # 7 doubles
    pairs = list(itertools.combinations(DEFECTS, 2))
    for _ in range(7):
        a, b = rng.choice(pairs)
        assignment.append({a, b})
    # 4 triples
    triples = list(itertools.combinations(DEFECTS, 3))
    for _ in range(4):
        t = rng.choice(triples)
        assignment.append(set(t))
    # 1 quadruple
    assignment.append(set(DEFECTS))
    rng.shuffle(assignment)
    return assignment


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="experiments/synthetic_test_set",
                    type=Path)
    ap.add_argument("--seed", default=42, type=int)
    args = ap.parse_args()

    rng = random.Random(args.seed)
    assignment = make_assignment(rng)
    args.out.mkdir(parents=True, exist_ok=True)

    cases = []
    for i, defects in enumerate(assignment, start=1):
        case_id = f"case_{i:03d}"
        tpl_name, tpl_fn = rng.choice(TEMPLATES)
        buggy, fixed = tpl_fn(defects)

        case_dir = args.out / case_id
        case_dir.mkdir(parents=True, exist_ok=True)
        # Use the same filename convention as Bugs4Q so iter_cases() picks
        # up these directories without modification.
        (case_dir / "buggy.py").write_text(buggy, encoding="utf-8")
        (case_dir / "fixed.py").write_text(fixed, encoding="utf-8")

        cases.append({
            "id": case_id,
            "defects": sorted(defects),
            "template": tpl_name,
            "source": buggy,
            "gold": fixed,
        })

    manifest = {
        "seed": args.seed,
        "n": len(cases),
        "defects_catalogue": DEFECTS,
        "templates": [name for name, _ in TEMPLATES],
        "distribution": {"single": 8, "double": 7, "triple": 4, "quadruple": 1},
        "layout": "Bugs4Q-compatible (case_dir/buggy.py + case_dir/fixed.py)",
        "cases": cases,
    }
    (args.out / "manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8")

    counts = {d: 0 for d in DEFECTS}
    by_size = {1: 0, 2: 0, 3: 0, 4: 0}
    by_tpl = {name: 0 for name, _ in TEMPLATES}
    lengths = []
    for c in cases:
        by_size[len(c["defects"])] += 1
        by_tpl[c["template"]] += 1
        lengths.append(len(c["source"].splitlines()))
        for d in c["defects"]:
            counts[d] += 1

    print(f"Generated {len(cases)} cases at {args.out}")
    print(f"Layout: each case has buggy.py + fixed.py "
          f"(Bugs4Q-compatible).")
    print()
    print(f"Length stats: min={min(lengths)}, max={max(lengths)}, "
          f"mean={sum(lengths)/len(lengths):.1f} lines")
    print()
    print("Distribution by defect count:")
    for k, v in by_size.items():
        print(f"  {k}-defect cases: {v}")
    print()
    print("Distribution by template:")
    for name, v in by_tpl.items():
        print(f"  {name:14s} {v:3d}")
    print()
    print("Per-defect occurrence counts:")
    for d in DEFECTS:
        print(f"  {d:24s} {counts[d]:4d}")


if __name__ == "__main__":
    main()
